package packages

import (
	"fmt"
	"os"
	"path/filepath"
)

const (
	DocFileName = "docs.go"

	DocFileTemplate = `// Code generated by ako; ADD YOUR DOCUMENTS.
package %s
`
)

func GenerateDocFile(path string) error {
	file, err := os.Create(filepath.Join(path, DocFileName))
	if err != nil {
		return err
	}
	defer file.Close()

	packageName := filepath.Base(path)
	if _, err := fmt.Fprintf(file, DocFileTemplate, packageName); err != nil {
		return err
	}

	if err := file.Sync(); err != nil {
		return err
	}

	return nil
}
